"""initial schema

Revision ID: 3d1fbc5097dc
Revises:
Create Date: 2026-04-02 08:30:49.824884

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d1fbc5097dc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amendment_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("base_intent_version", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("amended_brief_text", sa.Text(), nullable=False),
        sa.Column("is_breaking", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_amendment_proposals_intent_id"), "amendment_proposals", ["intent_id"], unique=False)
    op.create_table(
        "intent_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("intent_version", sa.Integer(), nullable=False),
        sa.Column("brief_text", sa.Text(), nullable=False),
        sa.Column("accepted_amendments", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intent_id", "intent_version", name="uq_intent_versions_intent_id_intent_version"),
    )
    op.create_index(op.f("ix_intent_versions_intent_id"), "intent_versions", ["intent_id"], unique=False)
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("lane", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("repo_access_set", sa.JSON(), nullable=False),
        sa.Column("envelope", sa.JSON(), nullable=False),
        sa.Column("repo_heads", sa.JSON(), nullable=False),
        sa.Column("planning_result", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pull_requests_intent_id"), "pull_requests", ["intent_id"], unique=False)
    op.create_index(op.f("ix_pull_requests_lane"), "pull_requests", ["lane"], unique=False)
    op.create_index(op.f("ix_pull_requests_worker_id"), "pull_requests", ["worker_id"], unique=False)
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("intent_id", sa.String(length=128), nullable=False),
        sa.Column("intent_version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("workflow_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["intent_id", "intent_version"],
            ["intent_versions.intent_id", "intent_versions.intent_version"],
            name="fk_cases_intent_versions",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_intent_id"), "cases", ["intent_id"], unique=False)
    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("repo", sa.String(length=255), nullable=False),
        sa.Column("lane", sa.String(length=64), nullable=False),
        sa.Column("step_type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planning",
                "ready",
                "leased",
                "running",
                "verifying",
                "succeeded",
                "failed",
                "revoked",
                name="stepstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("allowed_paths", sa.JSON(), nullable=False),
        sa.Column("forbidden_paths", sa.JSON(), nullable=False),
        sa.Column("base_commit", sa.String(length=64), nullable=True),
        sa.Column("target_branch", sa.String(length=255), nullable=True),
        sa.Column("artifact_requirements", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_steps_lane"), "steps", ["lane"], unique=False)
    op.create_index(op.f("ix_steps_repo"), "steps", ["repo"], unique=False)
    op.create_table(
        "leases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("lane", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("heartbeat_deadline", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=True),
        sa.Column("base_commit", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leases_expires_at"), "leases", ["expires_at"], unique=False)
    op.create_index(op.f("ix_leases_heartbeat_deadline"), "leases", ["heartbeat_deadline"], unique=False)
    op.create_index(op.f("ix_leases_lane"), "leases", ["lane"], unique=False)
    op.create_index(op.f("ix_leases_step_id"), "leases", ["step_id"], unique=False)
    op.create_index(op.f("ix_leases_worker_id"), "leases", ["worker_id"], unique=False)
    op.create_index(
        "uq_leases_active_step_id",
        "leases",
        ["step_id"],
        unique=True,
        postgresql_where=sa.text("expired_at IS NULL"),
        sqlite_where=sa.text("expired_at IS NULL"),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("lease_id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("repo", sa.String(length=255), nullable=False),
        sa.Column(
            "result_status",
            sa.Enum(
                "pending",
                "submitted",
                "accepted",
                "rejected",
                name="attemptresultstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("artifact_refs", sa.JSON(), nullable=False),
        sa.Column("submitted_diff_ref", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["leases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lease_id", name="uq_attempts_lease_id"),
    )
    op.create_index(op.f("ix_attempts_repo"), "attempts", ["repo"], unique=False)
    op.create_index(op.f("ix_attempts_step_id"), "attempts", ["step_id"], unique=False)
    op.create_index(op.f("ix_attempts_worker_id"), "attempts", ["worker_id"], unique=False)
    op.create_table(
        "verdicts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column(
            "result",
            sa.Enum(
                "pass",
                "fail_and_replan",
                "append_governance_step",
                "quarantine",
                "superseded",
                name="verdictresult",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verdicts_attempt_id"), "verdicts", ["attempt_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verdicts_attempt_id"), table_name="verdicts")
    op.drop_table("verdicts")
    op.drop_index(op.f("ix_attempts_worker_id"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_step_id"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_repo"), table_name="attempts")
    op.drop_table("attempts")
    op.drop_index(
        "uq_leases_active_step_id",
        table_name="leases",
        postgresql_where=sa.text("expired_at IS NULL"),
        sqlite_where=sa.text("expired_at IS NULL"),
    )
    op.drop_index(op.f("ix_leases_worker_id"), table_name="leases")
    op.drop_index(op.f("ix_leases_step_id"), table_name="leases")
    op.drop_index(op.f("ix_leases_lane"), table_name="leases")
    op.drop_index(op.f("ix_leases_heartbeat_deadline"), table_name="leases")
    op.drop_index(op.f("ix_leases_expires_at"), table_name="leases")
    op.drop_table("leases")
    op.drop_index(op.f("ix_steps_repo"), table_name="steps")
    op.drop_index(op.f("ix_steps_lane"), table_name="steps")
    op.drop_table("steps")
    op.drop_index(op.f("ix_cases_intent_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_pull_requests_worker_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_lane"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_intent_id"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_intent_versions_intent_id"), table_name="intent_versions")
    op.drop_table("intent_versions")
    op.drop_index(op.f("ix_amendment_proposals_intent_id"), table_name="amendment_proposals")
    op.drop_table("amendment_proposals")
    # ### end Alembic commands ###
